# Generated by Django 4.2.30 on 2026-08-03 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0009_alter_aaaarecord__ttl_alter_arecord__ttl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnszone",
            name="soa_serial",
            field=models.PositiveBigIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(4294967295),
                ],
            ),
        ),
    ]
