# Generated by Django 5.2.17 on 2026-08-24 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0010_aaaarecord_enabled_arecord_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnszone",
            name="soa_serial",
            field=models.PositiveBigIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(4294967295)]
            ),
        ),
    ]
